"""clawkit utils — Shared HTML report utilities."""


REPORT_CSS = """
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0f172a;color:#e2e8f0;padding:2rem}
h1{font-size:2rem;margin-bottom:0.25rem}
.subtitle{color:#94a3b8;margin-bottom:1.5rem}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}
.grid-4{grid-template-columns:repeat(4,1fr)}
.stat{background:#1e293b;padding:1rem;border-radius:0.75rem}
.stat-value{font-size:1.5rem;font-weight:700}
.stat-label{font-size:0.8rem;color:#94a3b8}
.card{background:#1e293b;border-radius:0.75rem;padding:1rem;margin-bottom:1rem}
table{width:100%;border-collapse:collapse;margin-top:1rem}
th{text-align:left;padding:0.5rem;background:#1e293b;border-bottom:2px solid #334155;font-size:0.8rem;color:#94a3b8}
td{padding:0.5rem;border-bottom:1px solid #334155;font-size:0.85rem}
code{color:#f87171}
.footer{margin-top:2rem;color:#64748b;font-size:0.8rem}
"""


def report_header(title, subtitle):
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{REPORT_CSS}</style></head><body>
<h1>{title}</h1><p class="subtitle">{subtitle}</p>"""


def report_footer():
    return f'<p class="footer">Generated by <strong>clawkit</strong></p></body></html>'
